# Forces new Travis-CI Infrastructure for faster builds
sudo: false
language: php

before_install:
  - pear upgrade pear

install:
  - pear install package.xml

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

script:
 - phpunit tests/
